# Generated by Django 3.2.8 on 2021-11-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
    ]
