# Generated by Django 3.1.13 on 2021-10-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.user', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'userdetail',
                'verbose_name_plural': 'userdetails',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='address label')),
                ('recipient', models.CharField(max_length=50, verbose_name="recipient's name")),
                ('phone', models.BigIntegerField(verbose_name='phone number')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postal_code', models.BigIntegerField(verbose_name='Postal Code')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetail', verbose_name='user detail ID')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresss',
            },
        ),
    ]
