# Generated by Django 3.2.8 on 2021-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone number'),
        ),
    ]
