# Generated by Django 3.2.8 on 2021-11-03 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='address label')),
                ('recipient', models.CharField(max_length=50, verbose_name="recipient's name")),
                ('phone', models.BigIntegerField(verbose_name='phone number')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postal_code', models.BigIntegerField(verbose_name='Postal Code')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocery.user'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
