# Generated by Django 3.2.8 on 2021-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Item Unit Title')),
            ],
            options={
                'verbose_name': 'Item Unit',
                'verbose_name_plural': 'Item Units',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.CharField(max_length=250, verbose_name='Image Url')),
                ('seller_price', models.BigIntegerField(verbose_name='Price from seller')),
                ('normal_price', models.BigIntegerField()),
                ('dicount_price', models.BigIntegerField(blank=True, default=None, null=True)),
                ('information', models.TextField(blank=True, verbose_name='Product Infromation')),
                ('nutrition', models.TextField(blank=True, verbose_name='Product Nutrition')),
                ('how_to_keep', models.TextField(blank=True, verbose_name='How To Keep')),
                ('categories', models.ManyToManyField(to='grocery.Category')),
                ('item_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grocery.itemunit', verbose_name='Item Unit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
