# Generated by Django 3.2.8 on 2021-11-08 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField(default=0, verbose_name='Price Total')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Item Unit Title')),
            ],
            options={
                'verbose_name': 'Item Unit',
                'verbose_name_plural': 'Item Units',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.CharField(max_length=250, verbose_name='Image Url')),
                ('normal_price', models.BigIntegerField()),
                ('dicount_price', models.BigIntegerField(blank=True, default=None, null=True)),
                ('information', models.TextField(verbose_name='Product Infromation')),
                ('nutrition', models.TextField(verbose_name='Product Nutrition')),
                ('how_to_keep', models.TextField(verbose_name='How To Keep')),
                ('categories', models.ManyToManyField(to='grocery.Category')),
                ('item_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grocery.itemunit', verbose_name='Item Unit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='product amount')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.cart', verbose_name='cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'cartproduct',
                'verbose_name_plural': 'cartproducts',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocery.user'),
        ),
    ]
