# Generated by Django 3.1.13 on 2021-10-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_unit',
            field=models.CharField(choices=[('pack', 'pack'), ('gram', 'gram'), ('kg', 'kg'), ('pcs', 'pcs')], max_length=10),
        ),
    ]
