# Generated by Django 3.2.8 on 2021-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_price',
            field=models.BigIntegerField(default=0, verbose_name='Price from seller'),
            preserve_default=False,
        ),
    ]
