# Generated by Django 3.2.8 on 2021-11-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211119_1012'),
        ('order', '0002_auto_20211119_1012'),
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
