# Generated by Django 3.2.8 on 2021-11-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_cartproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
