# Generated by Django 3.1.13 on 2021-10-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20211022_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
