# Generated by Django 3.1.13 on 2021-10-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20211022_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
