# Generated by Django 3.1.13 on 2021-10-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
