# Generated by Django 3.1.13 on 2021-10-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone number'),
        ),
    ]
