# Generated by Django 3.1.13 on 2021-10-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='grocery.Category'),
        ),
    ]
