# Generated by Django 3.1.13 on 2021-10-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_auto_20211014_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='product', to='grocery.Category'),
        ),
    ]
