# Generated by Django 3.1.13 on 2021-10-14 01:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0015_auto_20211014_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'buah')], max_length=32, null=True),
        ),
    ]
