# Generated by Django 3.1.13 on 2021-10-14 01:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0016_auto_20211014_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'buah'), ('2', 'sayur'), ('3', 'bumbu')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=[('1', 'buah'), ('2', 'sayur'), ('3', 'bumbu')], max_length=250),
        ),
    ]
