# Generated by Django 3.1.13 on 2021-10-14 01:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0017_auto_20211014_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
