# Generated by Django 3.1.13 on 2021-10-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0018_auto_20211014_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='grocery.Category'),
        ),
    ]
