# Generated by Django 3.1.13 on 2021-10-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifphone',
            name='count',
            field=models.BigIntegerField(default=0, verbose_name='otp count'),
        ),
        migrations.AlterField(
            model_name='unverifphone',
            name='phone',
            field=models.BigIntegerField(verbose_name='phone number'),
        ),
    ]
