# Generated by Django 3.2.8 on 2021-11-10 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grocery', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice Number')),
                ('order_status_code', models.SmallIntegerField(choices=[(0, 'Progress'), (1, 'Cancelled'), (2, 'on Deliver'), (3, 'Completed')], default=0, verbose_name='Order Status')),
                ('interact_status_code', models.SmallIntegerField(choices=[(0, 'Not replied yet'), (1, 'Said "YA" Already')], default=0, verbose_name='Interact Status')),
                ('invoice_status_code', models.SmallIntegerField(choices=[(0, 'Unpdaid'), (1, 'Paid'), (2, 'Issued')], default=0, verbose_name='Invoice Status')),
                ('total', models.FloatField(default=0, verbose_name='Order amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.useraddress', verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.user', verbose_name='user id')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.UUIDField()),
                ('at_price', models.BigIntegerField(verbose_name='At price')),
                ('qty', models.BigIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order ID')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
