# Generated by Django 3.2.8 on 2021-11-20 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grocery', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice Number')),
                ('order_status_code', models.SmallIntegerField(choices=[(0, 'Unverified'), (1, 'On Progress'), (2, 'On Delivery'), (3, 'Completed'), (4, 'Cancelled')], default=0, verbose_name='Order Status')),
                ('invoice_status_code', models.SmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Issued')], default=0, verbose_name='Invoice Status')),
                ('total', models.FloatField(default=0, verbose_name='Order amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.useraddress', verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.UUIDField()),
                ('at_price', models.BigIntegerField(verbose_name='At price')),
                ('qty', models.BigIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order ID')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='product amount')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart', verbose_name='cart')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocery.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'cartproduct',
                'verbose_name_plural': 'cartproducts',
            },
        ),
    ]
