# Generated by Django 3.2.8 on 2021-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_status_code',
            field=models.SmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Issued')], default=0, verbose_name='Invoice Status'),
        ),
    ]
