# Generated by Django 3.2.8 on 2021-11-10 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='at_price',
            field=models.BigIntegerField(default=0, verbose_name='At price'),
            preserve_default=False,
        ),
    ]
