# Generated by Django 3.2.8 on 2021-11-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status_code',
            field=models.SmallIntegerField(choices=[(0, 'Progress'), (1, 'Cancelled'), (2, 'on Deliver'), (3, 'Completed')], verbose_name='Order Status Code'),
        ),
    ]
