# Generated by Django 3.2.8 on 2021-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_at_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='interact_status_code',
            field=models.SmallIntegerField(choices=[(0, 'Not replied yet'), (1, 'Said "YA" Already')], default=0, verbose_name='Interact Status'),
        ),
    ]
