# Generated by Django 3.2.8 on 2021-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_invoice_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='interact_status_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status_code',
            field=models.SmallIntegerField(choices=[(0, 'Unverified'), (1, 'on Delivery'), (2, 'Completed')], default=0, verbose_name='Order Status'),
        ),
    ]
