# Generated by Django 3.2.8 on 2021-11-10 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0002_alter_order_order_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.UUIDField()),
                ('qty', models.BigIntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.useraddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Order amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status_code',
            field=models.SmallIntegerField(choices=[(0, 'Progress'), (1, 'Cancelled'), (2, 'on Deliver'), (3, 'Completed')], default=0, verbose_name='Order Status Code'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order ID'),
        ),
    ]
