# Generated by Django 3.2.8 on 2021-11-22 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
        ('order', '0002_alter_cartproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.BigIntegerField(default=1, verbose_name='product amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.product', verbose_name='Product'),
        ),
    ]
