# Generated by Django 3.2.8 on 2021-11-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211122_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, help_text='dont touch this field (auto add)', verbose_name='Total Invoice'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='at_price',
            field=models.BigIntegerField(default=0, help_text='dont touch this field (auto add)', verbose_name='At price (auto add)'),
        ),
    ]
