# Generated by Django 3.2.8 on 2021-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_interact_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status_code',
            field=models.SmallIntegerField(choices=[(0, 'Unpdaid'), (1, 'Paid'), (2, 'Issued')], default=0, verbose_name='Invoice Status Code'),
        ),
    ]
