version: "3"
services:
    db:
        container_name: grocery_db
        image: postgres:9.6-alpine
        volumes:
            - postgresdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: grocery
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
    app:
        container_name: grocery_app
        build: .
        ports:
            - "9090:8000"
        volumes:
            - ./:/app
        depends_on:
            - db
        environment:
            DEBUG: 1
            DEBUG_TOOLBAR: 1
            DATABASE_URL: postgres://postgres:secret@db:5432/grocery
volumes:
    postgresdata:
